[package]
name = "processing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"

#[lib]
#name = "processing_lib"
#path = "src/lib.rs"
